### ISSUE TITLE
Server Support?

### ISSUE THREAD

**Issue by Evigami** [MrJoshuaT/Fabric-Copper-Golem#1]
Please add server support! I must always be one step ahead of my friend's SMPs. Thank you :)!

**Comment by Evigami** [comment]
Aaaand I'm reopening it. Is there some way you could make the mod completely server-side? Possibly the clients have to install a texture pack or something? Thank you :)

**Comment by MrJoshuaT** [comment]
Unfortunately this is not possible, the clients require the mod so the game knows how to render the golems model, which includes a built-in golem resource pack for textures, if they don't have the mod they will see a Pig I believe

**Comment by Evigami** [comment]
Okay, thank you!

**Comment by Evigami** [comment]
One other thing @MrJoshuaT, Spawning the golem using the copper, Carved Pumpkin, and a Lightning rod doesn't seem to work.  All the blocks break and reappear and then the copper block becomes a server-side block that the client doesn't render. As this is the only way to spawn the golem in survival, it would be great if this works. Thank you!!!

**Comment by Evigami** [comment]
(Whoops clicked close with comment)

**Comment by MrJoshuaT** [comment]
Any chance you can attach a client log? I'll have some time to check this out manually tomorrow I hope

**Comment by MrJoshuaT** [comment]
Sorry I got ill and busy to update this before now. SalvieMundi has submitted a fix for servers, my silly mistake to why it was broken. I've published the newer version now (https://www.curseforge.com/minecraft/mc-mods/copper-golem-for-fabric/files), can you please let me know if this fixes your issues

**Comment by jexline** [comment]
I had no problems on my server, just saying. Also, this is the best Copper Golem mod I've ever seen :)

**Comment by 0gp** [comment]
tried copper-golem-1.0.1+1.17.1.jar, but it does not work on servers :(

**Comment by MrJoshuaT** [comment]
@0gp Indeed server support was only fixed in 1.18 build, I will pull that back for 1.17 and push a new version later today 🙂

**Comment by MrJoshuaT** [comment]
Servers should be supported. Please report this again if any issues occur
